name: dask-xgboost-test
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - codecov
  - dask
  - dask-glm >=0.2.0
  - distributed
  - flake8
  - isort==4.3.21
  - multipledispatch >=0.4.9
  - mypy
  - numba
  - numpy >=1.16.3
  - numpydoc
  - packaging
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-xdist
  - python=3.7.*
  - scikit-learn>=0.23.0
  - scipy
  - sparse
  - toolz
  - xgboost=0.90
